on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          args: --manifest-path wasm/Cargo.toml
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          args: --manifest-path wasm/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path wasm/Cargo.toml

  fmt:
    name: Rustfmt
    defaults:
      run:
        working-directory: wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          args: --manifest-path wasm/Cargo.toml
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          args: --manifest-path wasm/Cargo.toml
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path wasm/Cargo.toml --all -- --check

  #  clippy:
  #    name: Clippy
  #    defaults:
  #      run:
  #        working-directory: wasm
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #        with:
  #          args: --manifest-path wasm/Cargo.toml
  #      - uses: actions-rs/toolchain@v1
  #        with:
  #          profile: minimal
  #          toolchain: stable
  #          override: true
  #          args: --manifest-path wasm/Cargo.toml
  #      - run: rustup component add clippy
  #      - uses: actions-rs/cargo@v1
  #        with:
  #          command: clippy
  #          args: --manifest-path wasm/Cargo.toml -- -D warnings
  unit:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path wasm/Cargo.toml --workspace --lib
